### ISSUE TITLE
How can the material-expansionpanel-set work with sub componet?

### ISSUE THREAD

**Issue by sintak** [dart-lang/angular_components_example#100]
`<material-expansionpanel-set>
  <subcomponent *ngFor="let example of selected.examples"></subcomponent>
</material-expansionpanel-set>`

the subcomponent:
` <material-expansionpanel wide name="text" value="All conversions" [showSaveCancel]="false"
                [alwaysHideExpandIcon]="true">
</material-expansionpanel>`

then it no longer only allowing only one MaterialExpansionPanel open at a time.  That's unexpected

**Comment by nshahan** [comment]
Are you saying that you have wrapped the Material Expansion Panel component in your own custom component? Then you are adding your custom component as a child of the Material Expansion Panel Set?

**Comment by phantomesse** [comment]
Hi! The material expansion panel set is not intended to be used with a sub component that is not a material expansion panel. The material expansion panel component allows for a lot of customization, so it's generally unnecessary to use a wrapper component around it.

**Comment by sintak** [comment]
> `Are you saying that you have wrapped the Material Expansion Panel component in your own custom component? Then you are adding your custom component as a child of the Material Expansion Panel Set?`
Yes.

**Comment by sintak** [comment]
> Hi! The material expansion panel set is not intended to be used with a sub component that is not a material expansion panel. The material expansion panel component allows for a lot of customization, so it's generally unnecessary to use a wrapper component around it.

Thanks for the quick reply.
There is a lot of state and interaction between the expansionpanel component and its child components, so I want to make it a subcomponent. Now I have to try to use child components to maintain these states and interactions. Maybe it’s ugly but it works.
