### ISSUE TITLE
The Input "Auto SelectAll" example is not working on Safari 11.0

### ISSUE THREAD

**Issue by rxlabz** [dart-lang/angular_components_example#44]
On Safari 11/macOS 10.12, the example with the "Select all text" button works, but the "click to auto select field" doesn't.

**Comment by nshahan** [comment]
Thanks you are right. Interestingly I noticed that it does select the text eventually if you click the text, switch to a different app, and then switch back.

**Comment by nshahan** [comment]
This appears to be fixed in Safari since updating the examples.
