### ISSUE TITLE
Material popup doesn't work on iPad 2017 Chrome 64

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/angular_components_example#76]
Clicking on "OPEN POPUP" button changes the button text to "CLOSE POPUP" but doesn't open popup box.

https://dart-lang.github.io/angular_components_example/#/material_popup

Device info:
ipad 2017, MODEL MPGT2HN/A
iOS version : 10.3.3
Chrome 64.0.3282.112

**Comment by nshahan** [comment]
From an iPhone,  I can't recreate this issue on all of the popups on that page but the last one does not open.

**Comment by TedSander** [comment]
Just tried it on my ipad with the latest version and everything seems to be working for me. A slight delay but all the popups open.
