### ISSUE TITLE
Is there a way to reset material input state?

### ISSUE THREAD

**Issue by vadimzozulya** [dart-lang/angular_components_example#78]
[material_input example page](https://dart-lang.github.io/angular_components_example/#/material_input) has an example of using Form API. If RESET TEXT INPUT button is pressed when input value is invalid then the result is following: 
Text input is : initial text
Form validity is : INVALID
But the input still has validation error message:
![image](https://user-images.githubusercontent.com/10955191/39409349-30dfed06-4bee-11e8-8d57-cee2366c52bb.png)

How to reset input validation state ?

**Comment by chalin** [comment]
Might be related to: https://github.com/dart-lang/angular/issues/216, _Ability to reset form_

**Comment by nshahan** [comment]
@alorenzen Do we need an update in the example page?

**Comment by alorenzen** [comment]
I don't think we need to update the example page at this point. The button is just resetting the text, not the entire form state.

I'm actively working on dart-lang/angular#216. Until that's finished, nothing to do here.
