### ISSUE TITLE
custom tooltipShowDelay

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular_components_example#91]
Is it possible to make the delay to show the tooltip customizable ?

We need it to be shorter.
Something like that.
```html
<div [materialTooltip]="message" [delay]="300">
```

**Comment by TedSander** [comment]
Currently it isn't possible. We have talked about it before, it wouldn't be a input tho.

The problem we have is that it is weird if tooltip timing is different across different widgets. So it should be something that is set for the app or parts of the app and not individual components.

**Comment by nshahan** [comment]
Closing issue in this repo. If the feature gets added to the tooltips we will add an example or an explanation about how to customize.

**Comment by lejard-h** [comment]
@TedSander @nshahan 
could we use a value provider to have a global configuration

`ValueProvider.forToken<int>(meterialTooltipDelayToken, 300)`

Just saw that the issue is on the wrong repo, I can move it if you want to.

**Comment by nshahan** [comment]
Yes, feel free to open the issue in the other repo: https://github.com/dart-lang/angular_components/issues.
